console.log("hello world")

// git add . (Para adicionar os arquivos modificados.)
// git commit -m "Adicionando comentários sobre git." (Descrever a arvore de mudança, prendendo ele no arquivo.)
// git push (É o comando para subir online.)
// touch (Para criar arquivo: html, js e etc..)
// ls (Mostra todos os diretórios)
// cd + (nome do diretório) (Ele abre somente o diretório.)
// mkdir + (nome do diretorio) (Ele cria um novo diretório.)
// ls -a (Ele mostra tudo que possue dentro do diretório.)
// rm -rf + "nome" (Ele apaga o diretório)
